# Generated by Django 5.1.4 on 2024-12-29 05:38

import django.core.validators
import django.db.models.deletion
import utils.helper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentications",
            "0002_user_first_name_user_last_name_user_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.helper.content_file_path,
                verbose_name="Profile Picture",
            ),
        ),
        migrations.CreateModel(
            name="VendorInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="Business Name"),
                ),
                (
                    "business_email",
                    models.EmailField(max_length=255, verbose_name="Business Email"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Business Address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Contact Number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_information",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Information",
                "verbose_name_plural": "Vendors Information",
            },
        ),
    ]
