# Generated by Django 5.1.4 on 2024-12-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0003_user_profile_picture_vendorinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorinformation",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Active Status"),
        ),
    ]
