# Generated by Django 5.1.4 on 2024-12-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0004_vendorinformation_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendorinformation",
            old_name="is_active",
            new_name="approval_request",
        ),
    ]
