# Generated by Django 5.1.4 on 2024-12-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart_management", "0001_initial"),
        ("proudct_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="proudct_management.product",
            ),
        ),
    ]
